### ISSUE TITLE
How to specify output file name?

### ISSUE THREAD

**Issue by dpo** [jump-dev/KNITRO.jl#119]
The documentation says that the log file name can be changed via the `outname` option. I downloaded the `nlp1.jl` example and modified it like so:
```diff
diff --git a/nlp1.jl b/nlp1_mod.jl
index ebe64aa..6347a22 100644
--- a/nlp1.jl
+++ b/nlp1_mod.jl
@@ -89,9 +89,9 @@ kc = KNITRO.KN_new()
 
 # Illustrate how to override default options by reading from
 # the knitro.opt file.
-options = joinpath(dirname(@__FILE__), "..", "examples", "knitro.opt")
-KNITRO.KN_load_param_file(kc, options)
 KNITRO.KN_set_param(kc, "outlev", 3)
+KNITRO.KN_set_param(kc, "outmode", 2)
+KNITRO.KN_set_param(kc, "outname", "bla.log")
 
 # Initialize Knitro with the problem definition.
```
However, the output still goes to `knitro.log`:
```shell
dpo:/tmp $ date
Sat Jul  6 19:21:40 EDT 2019
dpo:/tmp $ julia nlp1_mod.jl   # output not shown but is normal
dpo:/tmp $ ll knitro.log
-rw-r--r--  1 dpo  wheel   4.5K Jul  6 19:21 knitro.log
dpo:/tmp $ ll bla.log
ls: bla.log: No such file or directory
```

Thanks.

**Comment by frapac** [comment]
This is a known bug in the solver Knitro, unfortunately... I have a (dirty) workaround to overcome this issue, till a fix is found in Knitro itself:

https://github.com/frapac/Knitro-Zoo/blob/master/opf/pglib/pglib_benchmark.jl#L107-L111

**Comment by odow** [comment]
If this is an upstream bug in KNITRO, was this resolved? It doesn't seem like there is anything actionable in KNITRO.jl.

**Comment by odow** [comment]
Closing because this doesn't seem to be a bug in KNITRO.jl.
