### ISSUE TITLE
Number of multipliers in callback

### ISSUE THREAD

**Issue by dpo** [jump-dev/KNITRO.jl#136]
I'm upgrading to KNITRO.jl 0.7.3 because previous versions don't build for me (Compat.jl doesn't appear in Project.toml).

I'm trying to solve a simple example problem with 2 variables and 1 constraint. However I'm puzzled by the fact that `evalRequest.lambda` in the callback is a vector of length 3. My tests used to pass and no longer do, so I presume something changed in KNITRO and/or KNITRO.jl. 
```julia
m = 1   # <-- this is the number of constraints that I register with KNITRO.KN_add_cons(kc, m)

=======================================
           Academic License
       (NOT FOR COMMERCIAL USE)
         Artelys Knitro 12.0.0
=======================================

No start point provided -- Knitro computing one.

Knitro presolve eliminated 0 variables and 0 constraints.

hessian_no_f:            1
Knitro changing algorithm from AUTO to 1.
Knitro changing bar_initpt from AUTO to 3.
Knitro changing bar_murule from AUTO to 4.
Knitro changing bar_penaltycons from AUTO to 0.
Knitro changing bar_penaltyrule from AUTO to 2.
Knitro changing bar_switchrule from AUTO to 0.
Knitro changing linesearch from AUTO to 1.
Knitro changing linsolver from AUTO to 2.

Problem Characteristics                                 (   Presolved)
-----------------------
Objective goal:  Minimize
Objective type:  general
Number of variables:                                  2 (           2)
    bounded below only:                               0 (           0)
    bounded above only:                               0 (           0)
    bounded below and above:                          0 (           0)
    fixed:                                            0 (           0)
    free:                                             2 (           2)
Number of constraints:                                1 (           1)
    linear equalities:                                0 (           0)
    quadratic equalities:                             0 (           0)
    gen. nonlinear equalities:                        1 (           1)
    linear one-sided inequalities:                    0 (           0)
    quadratic one-sided inequalities:                 0 (           0)
    gen. nonlinear one-sided inequalities:            0 (           0)
    linear two-sided inequalities:                    0 (           0)
    quadratic two-sided inequalities:                 0 (           0)
    gen. nonlinear two-sided inequalities:            0 (           0)
Number of nonzeros in Jacobian:                       2 (           2)
Number of nonzeros in Hessian:                        3 (           3)

  Iter      Objective      FeasError   OptError    ||Step||    CGits
--------  --------------  ----------  ----------  ----------  -------
       0    2.985498e+01   6.858e-01
ERROR: LoadError: DimensionMismatch("first array has length 1 which does not match the length of the second, 3.")
```
The error occurs in my code when I try to compute the dot product between the vector of constraints and the multipliers given in `evalRequest.lambda`.

Any ideas?

Thanks.

**Comment by frapac** [comment]
As you have 2 variables and 1 constraints, `evalRequest.lambda` should be of length 3 (2 reduced costs + one Lagrange multipliers). The order is as follows:
```
lambda = [multiplier_constraint_0 ; reduced_cost_variable_0, reduced_cost_variable_1]
```

However, I do not understand why your code was working with earlier version of `KNITRO.jl` (the code for callbacks does not change much during the previous months). Have you a MWE so that I could try to reproduce your issue?

**Comment by dpo** [comment]
I see. It's a bit strange to give the multipliers for bound constraints to evaluate the Hessian, so I thought that couldn't be the reason. I'm not sure why tests used to pass. The problem in question is one of the tests of NLPModelsKnitro, but it's not entirely trivial to reproduce as you would have to first try with the latest version of NLPModels, version 0.10.0, and then with 0.9.0.

At any rate, thank you. That should allow me to eliminate a bug somewhere.

**Comment by odow** [comment]
Closing as stale, and because there doesn't seem to be anything actionable here.
