### ISSUE TITLE
README.md clarification

### ISSUE THREAD

**Issue by ferrolho** [jump-dev/KNITRO.jl#220]
> _KNITRO.jl underwent a major rewrite between versions 0.12.0 and 0.13.0, (...)_

Shouldn't this read 0.11.0 and 0.12.0 instead?

**Comment by frapac** [comment]
Good question. In fact, the README is correct, it's just the version 0.13.0 has not been released yet. Maybe it's a good time to move forward on this.

**Comment by ferrolho** [comment]
I was about to delete this issue when I saw that the commit date that added that message to the README.md was _after_ v0.12 was released... :P Thanks for the prompt reply!

**Comment by frapac** [comment]
I think in semver the rules are different when a package has not reached its stable version (1.0) yet. In that case, we update only the minor digit to flag a breaking change. But a version 1.0 is coming soon!

**Comment by ferrolho** [comment]
I would argue that this package is already more than stable to deserve a 1.0 version. :P (Don't read this as a complaint, rather as a compliment.) But if there are breaking changes coming in soon, might as well get them in before tagging `v1.0`, I agree.

**Comment by frapac** [comment]
The release 0.13.0 is a major revamp of the C wrapper, and it brings some changes in the API if the users are using the low-level wrapper (no difference in MOI/JuMP). But it was worth doing before releasing a stable release, as it will considerably simplify future maintenance!

The current plan is to wait approx. one month before releasing Knitro.jl 1.0, just to give some time to detect potential errors in Knitro 0.13.0 so we have time to fix them before doing the stable release. It would be nice to fix also #180 #208

**Comment by ferrolho** [comment]
I can work on a PR for #180. Can you leave a reply on that issue as to how you think we should fix it?

**Comment by frapac** [comment]
Sure! Let me try to reproduce the issue first, then I think it should not be difficult to introduce a safeguard!
