### ISSUE TITLE
MathOptInterface.UnsupportedAttribute "maxtime_cpu"

### ISSUE THREAD

**Issue by jd-foster** [jump-dev/KNITRO.jl#222]
This came up on Discourse:
https://discourse.julialang.org/t/julia-with-knitro/81686/2

MWE
```
using JuMP
using KNITRO

m = Model(KNITRO.Optimizer)
set_optimizer_attribute(m, "maxtime_cpu", 3.6e+2)
```
gives
```
ERROR: MathOptInterface.UnsupportedAttribute
...
```
Cross-ref: https://www.artelys.com/docs/knitro//3_referenceManual/userOptions.html?highlight=maxtime_cpu#maxtime_cpu

**Comment by frapac** [comment]
Thanks for reporting this, I missed the original post on Discourse. 

I suspect the original post were using Knitro 13.0. This version renamed a few options to be consistent with the options used to tune the new parallel branch & bound algorithm implemented in this version. `maxtime_cpu` is one of these options, and has been renamed `maxtimecpu`. The following code works on my machine, with Knitro 13.0:
```julia


using JuMP
using KNITRO

m = Model(KNITRO.Optimizer)
set_optimizer_attribute(m, "maxtimecpu", 3.6e+2)

```

**Comment by jd-foster** [comment]
Ok, thanks. Does this mean that this line should updated?
https://github.com/jump-dev/KNITRO.jl/blob/460d60ac1f8bb51ad68c8ccc8a27b906ce060279/src/MOI_wrapper.jl#L287

Or did you mean that you intend to revert back to `maxcpu_time` rather than `maxcputime`?

**Comment by frapac** [comment]
I think we should update this line as well, not sure how it is handle internally in Knitro (it could be that `maxtime_cpu` is discarded if Knitro >= 13.0, leading to unexpected behavior). We just have to do the update carefully to maintain the compatibility with Knitro 12.*

> Or did you mean that you intend to revert back to maxcpu_time rather than maxcputime?

this is done internally in the Knitro solver, so not sure we can do anything here
