### ISSUE TITLE
Knitro.jl cannot handle Integer Variables

### ISSUE THREAD

**Issue by thiagonovaesb** [jump-dev/KNITRO.jl#244]
```
using JuMP
using KNITRO

model = Model(KNITRO.Optimizer)
@variable(model, x, Bin)
@objective(model, Max, x)
optimize!(model)
print(value(x))
```
Produce this:
```
ERROR: KN_add_con*() must be called before KN_get_var_lobnds().
ERROR: KN_add_con*() must be called before KN_get_var_upbnds().
0.0
```

**Comment by odow** [comment]
What is `soluution_summary(model)`?

And what if you have `@constraint(model, x >= 0)` before `optimize!`? This might happen because there are binary variables and no constraints.

**Comment by thiagonovaesb** [comment]
`solution_summary(model)` shows this?
```
* Solver : Knitro

* Status
  Termination status : OTHER_ERROR
  Primal status      : UNKNOWN_RESULT_STATUS
  Dual status        : UNKNOWN_RESULT_STATUS
  Message from the solver:
  "-515"

* Candidate solution
  Objective value      : 0.00000e+00
  Objective bound      : 0.00000e+00
  Relative gap         : 0.00000e+00

* Work counters
  Solve time (sec)   : 0.00000e+00
```

Actually, this is a small example, but I found this bug in another problem with a lot of constrains. So I tried add `@constraint(model, x >= 0)`, but it does not works.

**Comment by odow** [comment]
Hmm: problem is here:
https://github.com/jump-dev/KNITRO.jl/blob/685808fa2e634e32c9d648e5bb3abf84221b897a/src/MOI_wrapper/constraints.jl#L318-L329

Try: `@variable(model, 0 <= x <= 1, Bin)`

**Comment by Thiago-NovaesB** [comment]
@odow That didn't work either. I think we really need to check if the bounds exist before trying to get them. I opened a PR with a suggested fix.
