### ISSUE TITLE
MOI.set(model::Optimizer, ::MOI.NLPBlockDualStart, values) does not work

### ISSUE THREAD

**Issue by sjkobayashi** [jump-dev/KNITRO.jl#250]
I am trying to use `JuMP.set_nonlinear_dual_start_value` to set the initial values for duals, but it doesn't work because it seems like [`MOI.set(model::Optimizer, ::MOI.NLPBlockDualStart, values)`](https://github.com/jump-dev/KNITRO.jl/blob/4c56de7684c42dd3c83c5fbc515ae1f424eed524/src/MOI_wrapper/nlp.jl#LL39C1-L39C1) is left unfixed since fb1b4d5. If we replaced the body with something like `KN_set_con_dual_init_values(model.inner, length(model.nlp_index_cons), model.nlp_index_cons, values)`, would it work?

**Comment by odow** [comment]
I'm surprised the tests didn't catch this. Does it error, or just not set the right values?

Not sure on the fix, you'd have to try/check the KNITRO documentation: https://www.artelys.com/docs/knitro/3_referenceManual/callableLibraryAPI.html#KN_set_con_dual_init_values

Looks like we could use
```
KN_set_con_dual_init_values (      KN_context_ptr  kc,
                                             const KNINT           nC,
                                             const KNINT  * const  indexCons,
                                             const double * const  lambdaInitVals);
```
so `KN_set_con_dual_init_values(model.inner, length(model.nlp_index_cons), model.nlp_index_cons, values)` is on the right track.

You'd have to check that the `nlp_index_cons` were in the right order etc.

At the very least, we should remove this method so we're not doing something incorrect or claiming to support something we don't support.

**Comment by sjkobayashi** [comment]
Sorry should have been more precise. It throws the following error:
```
MethodError: no method matching KN_set_con_dual_init_values(::KNITRO.Model, ::Vector{Int32}, ::Vector{Float64})

Closest candidates are:
  KN_set_con_dual_init_values(::Any, ::Any, ::Any, !Matched::Any)
   @ KNITRO ~/.julia/packages/KNITRO/RJPC2/src/libknitro.jl:381
```
