### ISSUE TITLE
mcp type problems

### ISSUE THREAD

**Issue by Jovansam** [jump-dev/KNITRO.jl#253]
Artelys KNITRO has the capability to solve Mixed Complementarity Problems. It would be great if KNITRO.jl is updated to handle this class of problems as currently only PATH can be used from within JuMP to solve these problems.

**Comment by odow** [comment]
KNITRO supports `VectorOfVariables`-in-`Complements`, so something like `@constraint(model, x ⟂ y)` should work from JuMP?

Do you have an example where this doesn't work?

**Comment by odow** [comment]
Yes, this is because we haven't updated KNITRO to the new nonlinear syntax in MOI and JuMP: https://github.com/jump-dev/KNITRO.jl/issues/252

**Comment by odow** [comment]
Closing in favor of #252
