### ISSUE TITLE
Thoughts on the C interface

### ISSUE THREAD

**Issue by odow** [jump-dev/KNITRO.jl#267]
@frapac (and other watchers), I'd like to get feedback on potentially removing the `C_wrapper` part of the C API.

The main reason for removing it is because it is undocumented, and serves as a slightly complicated abstraction layer between MOI and the solver. It introduces a number of ways of doing the same thing:

https://github.com/jump-dev/KNITRO.jl/blob/4db649c9bce9750e7ac44579d957cc03e393de4d/src/C_wrapper.jl#L375-L402

and it uses multiple dispatch to create new functions that look like they're from the C API, but are actually not:

https://github.com/jump-dev/KNITRO.jl/blob/4db649c9bce9750e7ac44579d957cc03e393de4d/src/C_wrapper.jl#L703-L725

I've previously removed layers like this from Gurobi/CPLEX/etc and I think it is a big win. There is now only the MOI wrapper, and the upstream documented C API.

The downside, of course, is that there are a large number of examples using the C API, although we could update them to the underlying C:

https://github.com/jump-dev/KNITRO.jl/tree/master/examples

This would of course be horribly breaking, but it'd be nice to decide before releasing KNITRO v1.0.

I guess the other comparison here is Ipopt:

https://github.com/jump-dev/Ipopt.jl/blob/master/src/C_wrapper.jl

It has a very minimal C wrapper, which is mainly just to simplify the `@cccallable` stuff. So we wouldn't have to throw away the `C_wrapper.jl` entirely, just the bits that could otherwise be the original C.

**Comment by amontoison** [comment]
We use the C interfaces of Ipopt.jl and KNITRO.jl for the packages NLPModelsIpopt.jl and NLPModelsKnitro.jl.

**Comment by odow** [comment]
I guess to clarify, my change would mostly make it so that the _only_ `KN_xxx` functions are those defined in https://github.com/jump-dev/KNITRO.jl/blob/master/src/libknitro.jl

This would mostly affect calls like this, which, despite calling a `KN` function are not part of the KNITRO C API.
https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/blob/1603907741669101cf236af3c6ca11b13ed7c316/src/api.jl#L67-L71

But yes, this would be a breaking change, so we'd need to decide if it was worth it.

My point at the moment is that there is really 3 APIs that we are maintaining: MOI, `libknitro.jl`, and the in-between kinda-c-and-kinda-julia.

**Comment by odow** [comment]
Perhaps let me draft a PR, and then we will have something more concrete to discuss.

**Comment by odow** [comment]
Another problem with the C wrapper is that it just ignores all return codes, so we're not catching errors.

**Comment by frapac** [comment]
@odow I agree with you: the current C wrapper is a bit clunky, and was developed before Clang.jl has been made broadly available. 

In general, I prefer simplicity.

If you want, I can update the examples with the new bare-bone C wrapper.

**Comment by odow** [comment]
I've made good progress https://github.com/jump-dev/KNITRO.jl/pull/268. I have't updated the examples yet.

The `C_wrapper.jl` is now basically only that what is needed to create the callbacks for C and Julia.

**Comment by odow** [comment]
I'm now much more confidence about the state of the KNITRO C wrapper, and I think simplifying it is a very good idea. The C examples were trivial to update, and in every case, they made things much more explicit.

If we merge this, I'll be responsible for updating NLPModelsKnitro.

**Comment by odow** [comment]
I updated NLPModelsKnitro: https://github.com/JuliaSmoothOptimizers/NLPModelsKnitro.jl/pull/117, so I think I'm ready to release v0.14.

**Comment by odow** [comment]
Closing because I'm now pretty happy with the C wrapper.

The only changes are around `KN_new` and `KN_free`, the license manager, callbacks, `KN_solve` (because of the multithreading issue) and the novel `KN_solution(::Model)`.

This should be much easier to debug and maintain going forwards.
