### ISSUE TITLE
KNITRO errors and breakages.

### ISSUE THREAD

**Issue by iajzenszmi** [jump-dev/KNITRO.jl#292]
<pre><b>ansion</b>
  <font color="#555753">    @</font> <font color="#555753">~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/</font><font color="#555753"><u style="text-decoration-style:single">Test.jl:1577</u></font><font color="#555753"> [inlined]</font>
    [9] top-level scope
  <font color="#555753">    @</font> <font color="#555753">~/.julia/packages/KNITRO/FWSi0/test/</font><font color="#555753"><u style="text-decoration-style:single">runtests.jl:12</u></font>
   [10] <b>include(</b><font color="#555753">fname</font>::String<b>)</b>
  <font color="#555753">    @</font> <font color="#555753">Base.MainInclude</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:489</u></font>
   [11] top-level scope
  <font color="#555753">    @</font> <font color="#555753"><u style="text-decoration-style:single">none:6</u></font>
   [12] <b>eval</b>
  <font color="#555753">    @</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">boot.jl:385</u></font><font color="#555753"> [inlined]</font>
   [13] <b>exec_options(</b><font color="#555753">opts</font>::Base.JLOptions<b>)</b>
  <font color="#555753">    @</font> <font color="#555753">Base</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:291</u></font>
   [14] <b>_start()</b>
  <font color="#555753">    @</font> <font color="#555753">Base</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:552</u></font>
Test C API: <font color="#EF2929"><b>Error During Test</b></font> at <b>/home/ian/.julia/packages/KNITRO/FWSi0/test/runtests.jl:11</b>
  Got exception outside of a @test
  LoadError: could not load symbol &quot;KTR_get_release&quot;:
  /home/ian/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/bin/julia: undefined symbol: KTR_get_release
  Stacktrace:
    [1] <b>knitro_version()</b>
  <font color="#555753">    @</font> <font color="#75507B">KNITRO</font> <font color="#555753">~/.julia/packages/KNITRO/FWSi0/src/</font><font color="#555753"><u style="text-decoration-style:single">KNITRO.jl:39</u></font>
    [2] top-level scope
  <font color="#555753">    @</font> <font color="#555753">~/.julia/packages/KNITRO/FWSi0/test/</font><font color="#555753"><u style="text-decoration-style:single">C_wrapper.jl:98</u></font>
    [3] <b>include(</b><font color="#555753">fname</font>::String<b>)</b>
  <font color="#555753">    @</font> <font color="#555753">Base.MainInclude</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:489</u></font>
    [4] <b>macro expansion</b>
  <font color="#555753">    @</font> <font color="#555753">~/.julia/packages/KNITRO/FWSi0/test/</font><font color="#555753"><u style="text-decoration-style:single">runtests.jl:12</u></font><font color="#555753"> [inlined]</font>
    [5] <b>macro expansion</b>
  <font color="#555753">    @</font> <font color="#555753">~/.julia/juliaup/julia-1.10.2+0.x64.linux.gnu/share/julia/stdlib/v1.10/Test/src/</font><font color="#555753"><u style="text-decoration-style:single">Test.jl:1577</u></font><font color="#555753"> [inlined]</font>
    [6] top-level scope
  <font color="#555753">    @</font> <font color="#555753">~/.julia/packages/KNITRO/FWSi0/test/</font><font color="#555753"><u style="text-decoration-style:single">runtests.jl:12</u></font>
    [7] <b>include(</b><font color="#555753">fname</font>::String<b>)</b>
  <font color="#555753">    @</font> <font color="#555753">Base.MainInclude</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:489</u></font>
    [8] top-level scope
  <font color="#555753">    @</font> <font color="#555753"><u style="text-decoration-style:single">none:6</u></font>
    [9] <b>eval</b>
  <font color="#555753">    @</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">boot.jl:385</u></font><font color="#555753"> [inlined]</font>
   [10] <b>exec_options(</b><font color="#555753">opts</font>::Base.JLOptions<b>)</b>
  <font color="#555753">    @</font> <font color="#555753">Base</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:291</u></font>
   [11] <b>_start()</b>
  <font color="#555753">    @</font> <font color="#555753">Base</font> <font color="#555753">./</font><font color="#555753"><u style="text-decoration-style:single">client.jl:552</u></font>
  in expression starting at /home/ian/.julia/packages/KNITRO/FWSi0/test/C_wrapper.jl:98
<b>Test Summary:         | </b><font color="#EF2929"><b>Error  </b></font><font color="#34E2E2"><b>Total  </b></font><b>Time</b>
Test C API            | <font color="#EF2929">    2  </font><font color="#06989A">    2  </font>1.9s
  Definition of model | <font color="#EF2929">    1  </font><font color="#06989A">    1  </font>1.6s
<font color="#EF2929"><b>ERROR: </b></font>LoadError: <font color="#EF2929">Some tests did not pass: 0 passed, 0 failed, 2 errored, 0 broken.</font>
in expression starting at /home/ian/.julia/packages/KNITRO/FWSi0/test/runtests.jl:11
<font color="#EF2929"><b>ERROR: </b></font>Package KNITRO errored during testing
</pre>

**Comment by odow** [comment]
Do you have KNITRO installed? https://github.com/jump-dev/KNITRO.jl?tab=readme-ov-file#installation What version?

**Comment by odow** [comment]
Closing as stale. It doesn't appear that the user has KNITRO installed.

If you have KNITRO installed and the issue persists, please comment and I will re-open the issue.
