### ISSUE TITLE
Wrap KNITRO's callbacks inside MOI

### ISSUE THREAD

**Issue by frapac** [jump-dev/KNITRO.jl#92]
Currently, only generic NLP callbacks (eval_f, eval_g, eval_h) are handled inside `MOI_wrapper`. However, KNITRO 11 supports other callbacks: 
- evaluation callbacks for least-square models (cf `KN_add_lsq_eval_callback` and `KN_set_cb_rsd_jac`)
- new estimate callbacks, called each time KNITRO computes a new estimate of the solution points (cf `KN_set_newpt_callback`) 
- MIP node callbacks (cf `KN_set_mip_node_callback`) 
- Multistart callbacks (cf `KN_set_ms_process_callback`)
- Print callback (cf `KN_set_puts_callback`) 

We should wrap these different callbacks in MOI, for instance by following the procedure specified in [MOI documentation](http://www.juliaopt.org/MathOptInterface.jl/stable/apimanual/#Solver-specific-attributes-1). That would give, for instance for the MIP node callback: 

```julia
struct MIPNodeCallback <: MOI.AbstractOptimizerAttribute
    function::Function
    mip_params 
end
function MOI.set(model::Optimizer, callback::MIPNodeCallback, level::Int)
    # ... set MIP node callback ...
    KN_set_mip_node_callback(model.inner, callback.function) 
    # set params 
    ...
end
```

**Comment by odow** [comment]
Closing as won't-fix for now. If anyone comes across this and needs it, please comment and we can revisit the idea.
